@echo off
:: ===========================================================
::  Mwalimu Cosmetics - till PC. ONE-TIME SETUP.
::
::  Run this ONCE on every PC except the hub. It is the LAST
::  time anyone needs to walk to that machine. After this:
::
::    * the PC checks the hub every 10 minutes and stages any
::      new FumasV5 build by itself, with no internet;
::    * the laptop can run commands on it remotely, so future
::      fixes do not need a visit at all.
::
::  Right-click this file -> Run as administrator.
::
::  Plain ASCII and no multi-line continuations: both have
::  already broken a script in this folder once.
:: ===========================================================

setlocal

:: The hub set up by setup-hub.bat. Change HUB here if the
:: share ends up on a different machine.
set "HUB=10.10.10.4"
set "SHARENAME=updates"
set "SHAREUSER=mwalimuupd"
set "SHAREPASS=MwalimuUpd2026"

:: A consistent local administrator across every shop PC, so
:: the laptop has one credential rather than four.
set "ADMUSER=mwalimuadmin"
set "ADMPASS=MwalimuAdmin2026"

set "LOCALDIR=C:\MwalimuSync"

title Mwalimu Cosmetics - set up this PC for remote updates

net session >nul 2>&1
if errorlevel 1 (
  echo.
  echo  [STOP] This needs administrator rights.
  echo         Right-click %~nx0 and choose "Run as administrator".
  echo.
  pause
  exit /b 1
)

echo.
echo  ==========================================================
echo   Setting up %COMPUTERNAME% for remote updates
echo   Hub: \\%HUB%\%SHARENAME%
echo  ==========================================================
echo.

:: --- 1. Check the hub is actually reachable -----------------
:: Doing this first means a typo or an unplugged cable is
:: reported now, not silently every 10 minutes forever.
net use "\\%HUB%\%SHARENAME%" /user:%SHAREUSER% %SHAREPASS% >nul 2>&1
if errorlevel 1 (
  echo  [STOP] Cannot reach \\%HUB%\%SHARENAME%
  echo.
  echo         Check that setup-hub.bat has been run on %HUB%,
  echo         and that the ethernet cable is connected.
  echo.
  pause
  exit /b 1
)
echo  [OK] Hub share is reachable
net use "\\%HUB%\%SHARENAME%" /delete >nul 2>&1

if not exist "%LOCALDIR%" mkdir "%LOCALDIR%" 2>nul

:: --- 2. The bootstrap the scheduled task runs ---------------
:: Deliberately tiny. All the real logic lives in check.cmd ON
:: THE SHARE, so it can be changed centrally later without
:: anyone walking back to this machine.
set "BOOT=%LOCALDIR%\lan-update.cmd"
> "%BOOT%" echo @echo off
>>"%BOOT%" echo :: Generated by setup-pc.bat - do not edit here.
>>"%BOOT%" echo :: The real logic is in \\%HUB%\%SHARENAME%\agent\check.cmd
>>"%BOOT%" echo net use "\\%HUB%\%SHARENAME%" /user:%SHAREUSER% %SHAREPASS% ^>nul 2^>^&1
>>"%BOOT%" echo if errorlevel 1 exit /b 0
>>"%BOOT%" echo if exist "\\%HUB%\%SHARENAME%\agent\check.cmd" call "\\%HUB%\%SHARENAME%\agent\check.cmd"
>>"%BOOT%" echo net use "\\%HUB%\%SHARENAME%" /delete ^>nul 2^>^&1
>>"%BOOT%" echo exit /b 0
echo  [OK] Update bootstrap written to %BOOT%

:: --- 3. Run it every 10 minutes -----------------------------
schtasks /query /tn "MwalimuLanUpdate" >nul 2>&1
if not errorlevel 1 schtasks /delete /tn "MwalimuLanUpdate" /f >nul 2>&1
schtasks /create /tn "MwalimuLanUpdate" /tr "cmd /c \"%BOOT%\"" /sc minute /mo 10 /ru SYSTEM /rl HIGHEST /f >nul
if errorlevel 1 (
  echo  [WARN] Could not register the scheduled task.
  echo         Updates will not arrive automatically on this PC.
) else (
  echo  [OK] Scheduled task MwalimuLanUpdate - every 10 minutes
)

:: --- 4. Remote administration from the laptop ---------------
net user %ADMUSER% >nul 2>&1
if errorlevel 1 (
  net user %ADMUSER% %ADMPASS% /add /comment:"Mwalimu remote administration" /passwordchg:no >nul
  echo  [OK] Created admin account %ADMUSER%
) else (
  net user %ADMUSER% %ADMPASS% >nul
  echo  [OK] Account %ADMUSER% already existed - password reset
)
powershell -NoProfile -Command "Set-LocalUser -Name '%ADMUSER%' -PasswordNeverExpires $true" >nul 2>&1
net localgroup Administrators %ADMUSER% /add >nul 2>&1

:: Without this, a LOCAL account arriving over the network is
:: stripped of its administrator token and every remote command
:: fails with access denied - which is exactly what \\PC\C$ did
:: from the laptop before this script existed.
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1 /f >nul 2>&1

netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=Yes >nul 2>&1
netsh advfirewall firewall set rule group="Windows Management Instrumentation (WMI)" new enable=Yes >nul 2>&1

:: -SkipNetworkProfileCheck: shop PCs often sit on a network
:: Windows has decided is "Public", where this otherwise refuses.
powershell -NoProfile -Command "try { Enable-PSRemoting -Force -SkipNetworkProfileCheck | Out-Null; exit 0 } catch { exit 1 }" >nul 2>&1
if errorlevel 1 (
  echo  [WARN] Remote PowerShell could not be enabled on this PC.
  echo         Updates still work; only run-on-all.ps1 will skip it.
) else (
  echo  [OK] Remote PowerShell enabled
)

echo.
echo  ==========================================================
echo   %COMPUTERNAME% is set up.
echo.
echo   This PC now checks \\%HUB%\%SHARENAME% every 10 minutes.
echo   A new build is staged automatically and applied the next
echo   time the POS is opened with the Mwalimu shortcut.
echo.
echo   To test it now, without waiting:
echo       schtasks /run /tn MwalimuLanUpdate
echo.
echo   Log: %LOCALDIR%\lan-update.log
echo  ==========================================================
echo.
pause
