/**
 * Turn the schema probe's JSON capture into loadable .sql files.
 *
 * The probe ships JSON because that is what the existing backup endpoint
 * accepts. This converts it into something you can feed straight into a MySQL
 * instance to recreate the structure — which is what the test database and
 * any disaster recovery actually need.
 *
 * Usage: node db/build-sql.js
 */

const fs   = require("fs");
const path = require("path");

const RAW = path.join(__dirname, "_phase0-raw");
const OUT = __dirname;

function read(name) {
  const p = path.join(RAW, `${name}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

const vars = read("vars");
const header = (title) => [
  `-- ${title}`,
  `-- Captured from the live database by bridge/schema-probe.js`,
  vars ? `-- Source: MySQL ${vars[0].version}, sql_mode '${vars[0].sql_mode}', captured ${vars[0].server_time}` : "",
  `-- Generated by db/build-sql.js — do not edit by hand.`,
  "",
].filter(Boolean).join("\n");

// ── Schema ──────────────────────────────────────────────────────
const schema = read("schema");
if (schema) {
  const out = [header("mwalimuinvest — table structure")];
  out.push("SET FOREIGN_KEY_CHECKS = 0;\n");

  let ok = 0, failed = [];
  for (const { table, ddl, error } of schema) {
    if (!ddl) { failed.push(`${table} (${error || "no DDL"})`); continue; }
    out.push(`-- ${"-".repeat(60)}`);
    out.push(`DROP TABLE IF EXISTS \`${table}\`;`);
    out.push(`${ddl};`);
    out.push("");
    ok++;
  }
  out.push("SET FOREIGN_KEY_CHECKS = 1;");
  if (failed.length) out.push(`\n-- NOT CAPTURED: ${failed.join(", ")}`);

  fs.writeFileSync(path.join(OUT, "schema.sql"), out.join("\n"), "utf8");
  console.log(`schema.sql   — ${ok} tables${failed.length ? `, ${failed.length} failed` : ""}`);
}

// ── Routines ────────────────────────────────────────────────────
// These exist nowhere else. do_stock_transactions is the only path by which
// stock is ever written, so this file is the single most valuable artefact
// the probe produces.
const routines = read("routines");
if (routines) {
  const out = [header("mwalimuinvest — stored procedures and functions")];
  out.push("DELIMITER $$\n");

  let ok = 0, failed = [];
  for (const { name, type, ddl, error } of routines) {
    if (!ddl) { failed.push(`${name} (${error || "no DDL"})`); continue; }
    // DEFINER ties the routine to an account that may not exist on a restore
    // target, so strip it and let the restoring user own them.
    const body = ddl.replace(/DEFINER\s*=\s*`[^`]*`@`[^`]*`\s*/i, "");
    out.push(`-- ${"-".repeat(60)}`);
    out.push(`DROP ${type} IF EXISTS \`${name}\`$$`);
    out.push(`${body}$$`);
    out.push("");
    ok++;
  }
  out.push("DELIMITER ;");
  if (failed.length) out.push(`\n-- NOT CAPTURED: ${failed.join(", ")}`);

  fs.writeFileSync(path.join(OUT, "routines.sql"), out.join("\n"), "utf8");
  const procs = routines.filter(r => r.type === "PROCEDURE").length;
  console.log(`routines.sql — ${ok} routines (${procs} procedures, ${ok - procs} functions)${failed.length ? `, ${failed.length} failed` : ""}`);
}

// ── Engines ─────────────────────────────────────────────────────
const engines = read("engines");
if (engines) {
  const LEDGER = ["pos_header", "pos_details", "pos_payment_details",
                  "journal_transactions", "creditors_transactions",
                  "stran", "nauto", "ap_prepayment", "accounts"];
  const bad = engines.filter(e => LEDGER.includes(e.name) &&
                                  String(e.engine).toLowerCase() !== "innodb");
  console.log(bad.length
    ? `engines      — WARNING: not InnoDB: ${bad.map(e => `${e.name}=${e.engine}`).join(", ")}`
    : `engines      — all ledger tables InnoDB`);
} else {
  console.log("engines      — not captured; re-run the probe for this");
}
