-- mwalimuinvest — stored procedures and functions
-- Captured from the live database by bridge/schema-probe.js
-- Source: MySQL 5.1.73-community, sql_mode 'IGNORE_SPACE', captured 2026-08-01T08:46:50.000Z
-- Generated by db/build-sql.js — do not edit by hand.
DELIMITER $$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `check_qty_category`$$
CREATE FUNCTION `check_qty_category`(v_code VARCHAR(200)) RETURNS int(3)
    DETERMINISTIC
BEGIN
       DECLARE bname   int(3);
          
          select checkqty into bname from sc where code =get_category(v_code,'Stocks')   limit 1;
     
        RETURN ifnull(bname,1);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_accountname`$$
CREATE FUNCTION `get_accountname`(v_NAME VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname  VARCHAR(200);
          
          SELECT description INTO bname  from accounts where code=v_NAME limit 1;
               
        RETURN ifnull(bname,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_accounts_cogs`$$
CREATE FUNCTION `get_accounts_cogs`(v_code VARCHAR(200),v_cogs_ac VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_cogs VARCHAR(200);

          SELECT  if((cost_of_sales='' or cost_of_sales is null),v_cogs_ac,cost_of_sales) INTO s_cogs from si where code =v_code LIMIT 1 ;

         RETURN IFNULL(s_cogs,v_cogs_ac);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_accounts_discount`$$
CREATE FUNCTION `get_accounts_discount`(v_code VARCHAR(200),discount_ac VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE v_discount_ac VARCHAR(200);

          SELECT  if((discaccount='' or discaccount is null),discount_ac,discaccount) INTO v_discount_ac from si where code =v_code LIMIT 1 ;

         RETURN IFNULL(v_discount_ac,discount_ac);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_accounts_inventory`$$
CREATE FUNCTION `get_accounts_inventory`(v_code VARCHAR(200),v_inventory_ac VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_inventory VARCHAR(200);

          SELECT  if((inventory='' or inventory is null),v_inventory_ac,inventory) INTO s_inventory from si where code =v_code LIMIT 1 ;

         RETURN IFNULL(s_inventory,v_inventory_ac);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_accounts_revenue`$$
CREATE FUNCTION `get_accounts_revenue`(v_code VARCHAR(200),revenue_ac VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE v_revenue_ac VARCHAR(200);

          SELECT  if((revenue='' or revenue is null),revenue_ac,revenue) INTO v_revenue_ac from si where code =v_code LIMIT 1 ;

         RETURN IFNULL(v_revenue_ac,revenue_ac);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_aircraft_type`$$
CREATE FUNCTION `get_aircraft_type`(v_type VARCHAR(200)) RETURNS int(12)
    DETERMINISTIC
BEGIN
       DECLARE bname int(12);
          select ifnull(count(*),1) INTO bname from aircraft where pcategory=v_type ;     
           
		RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_allocation_ratio`$$
CREATE FUNCTION `get_allocation_ratio`(v_orderno VARCHAR(200)) RETURNS decimal(20,4)
    DETERMINISTIC
BEGIN
       DECLARE s_total DECIMAL(20,4);

	SELECT sum(abs(amountpaid)) INTO s_total  FROM ar_allocations_details WHERE  remarks<>'INVOICE' and rno=v_orderno GROUP BY rno;

         RETURN IFNULL(s_total ,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_ap_paid`$$
CREATE FUNCTION `get_ap_paid`(V_type VARCHAR(200),V_invno VARCHAR(200),v_dateto VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_type<>'RECEIPTS' THEN 

          IF V_type='INVOICE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (
           SELECT sum(b.amountpaid) AS amountpaid from  ap_prepayment a,ap_prepayment_details b where a.pno=b.rno and  invno=V_invno and pdate<=v_dateto AND posted=1
            union all
           select sum(abs(b.amountpaid)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='INVOICE' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

          IF V_type='CREDITNOTE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (           
           select sum(abs(b.amountpaid)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='CREDIT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

        END IF;

       IF V_type='RECEIPTS' THEN 
         SELECT  SUM(amountpaid) INTO s_qty FROM (
         SELECT sum(b.amountpaid) AS amountpaid from  ap_prepayment a,ap_prepayment_details b where a.pno=b.rno and  a.pno=V_invno and pdate<=v_dateto AND posted=1
          union all
         select sum(abs(b.amountpaid)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='RECEIPT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
          ) AS A;
        END IF;

        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_ap_paid_2`$$
CREATE FUNCTION `get_ap_paid_2`(V_type VARCHAR(200),V_invno VARCHAR(200),v_dateto VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        
       IF V_type<>'RECEIPTS' THEN 
         SELECT  SUM(amountpaid) INTO s_qty FROM (
         SELECT sum(b.amountpaid) AS amountpaid from  ap_prepayment a,ap_prepayment_details b where a.pno=b.rno and  a.pno=V_invno and pdate<=v_dateto AND posted=1
          union all
         select sum(abs(b.amountpaid)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='RECEIPT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
          ) AS A;
        END IF;

        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_ap_paid_tran_rate`$$
CREATE FUNCTION `get_ap_paid_tran_rate`(V_type VARCHAR(200),V_invno VARCHAR(200),v_dateto VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_type<>'RECEIPTS' THEN 

          IF V_type='INVOICE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (
           SELECT sum(b.amountpaid/b.rate) AS amountpaid from  ap_prepayment a,ap_prepayment_details b where a.pno=b.rno and  invno=V_invno and pdate<=v_dateto AND posted=1
            union all
           select sum(abs(b.amountpaid/rate)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='INVOICE' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

          IF V_type='CREDITNOTE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (           
           select sum(abs(b.amountpaid/rrate)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='CREDIT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

        END IF;

       IF V_type='RECEIPTS' THEN 
         SELECT  SUM(amountpaid) INTO s_qty FROM (
         SELECT sum(b.amountpaid/a.rate) AS amountpaid from  ap_prepayment a,ap_prepayment_details b where a.pno=b.rno and  a.pno=V_invno and pdate<=v_dateto AND posted=1
          union all
         select sum(abs(b.amountpaid/rrate)) AS amountpaid from ap_allocations a,ap_allocations_details b where a.rno=b.rno and remarks='RECEIPT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
          ) AS A;
        END IF;

        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_ar_paid`$$
CREATE FUNCTION `get_ar_paid`(V_type VARCHAR(200),V_invno VARCHAR(200),v_dateto VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_type<>'RECEIPTS' THEN 

          IF V_type='INVOICE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (
           SELECT sum(b.amountpaid) AS amountpaid from  ar_prepayment a,ar_prepayment_details b where a.pno=b.rno and  invno=V_invno and pdate<=v_dateto AND posted=1
            union all
           select sum(abs(b.amountpaid)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='INVOICE' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

          IF V_type='CREDITNOTE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (           
           select sum(abs(b.amountpaid)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='CREDIT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

        END IF;

       IF V_type='RECEIPTS' THEN 
         SELECT  SUM(amountpaid) INTO s_qty FROM (
         SELECT sum(b.amountpaid) AS amountpaid from  ar_prepayment a,ar_prepayment_details b where a.pno=b.rno and  a.pno=V_invno and pdate<=v_dateto AND posted=1
          union all
         select sum(abs(b.amountpaid)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='RECEIPT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
          ) AS A;
        END IF;

        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_ar_paid_tran_rate`$$
CREATE FUNCTION `get_ar_paid_tran_rate`(V_type VARCHAR(200),V_invno VARCHAR(200),v_dateto VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_type<>'RECEIPTS' THEN 

          IF V_type='INVOICE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (
           SELECT sum(b.amountpaid/b.rate) AS amountpaid from  ar_prepayment a,ar_prepayment_details b where a.pno=b.rno and  invno=V_invno and pdate<=v_dateto AND posted=1
            union all
           select sum(abs(b.amountpaid/rate)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='INVOICE' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

          IF V_type='CREDITNOTE' THEN
           SELECT  SUM(amountpaid) INTO s_qty FROM (           
           select sum(abs(b.amountpaid/rrate)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='CREDIT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
           ) AS A;
          END IF;

        END IF;

       IF V_type='RECEIPTS' THEN 
         SELECT  SUM(amountpaid) INTO s_qty FROM (
         SELECT sum(b.amountpaid/a.rate) AS amountpaid from  ar_prepayment a,ar_prepayment_details b where a.pno=b.rno and  a.pno=V_invno and pdate<=v_dateto AND posted=1
          union all
         select sum(abs(b.amountpaid/rrate)) AS amountpaid from ar_allocations a,ar_allocations_details b where a.rno=b.rno and remarks='RECEIPT' AND INVNO=V_invno AND rdate<=v_dateto  AND posted=1 
          ) AS A;
        END IF;

        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_average_cost`$$
CREATE FUNCTION `get_average_cost`(v_no VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname  DOUBLE;
         
       SELECT ifnull(SUM(if(type='INPUT',qty*uprice,0))/SUM(if(type='OUTPUT',qty*weight,0)),0) INTO bname  FROM ass_d where no=v_no ;
         
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_average_cost_p`$$
CREATE FUNCTION `get_average_cost_p`(v_no VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname  DOUBLE;
         
       SELECT ifnull(SUM(if(type<>'OUTPUT',qty*uprice,0))/SUM(if(type='OUTPUT',qty*weight,0)),0) INTO bname  FROM Packing_d where no=v_no  group by no limit 1 ;
         
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_average_cost_p_id`$$
CREATE FUNCTION `get_average_cost_p_id`(v_no VARCHAR(200),id_no VARCHAR(200),has_bom VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname  DOUBLE;
         
         
		  IF  has_bom='1' THEN
          SELECT ifnull(SUM(if(type<>'OUTPUT' and unique_id=id_no,qty*uprice,0))/SUM(if(type='OUTPUT'  and adid=id_no,qty*weight,0)),0) INTO bname  FROM Packing_d where no=v_no group by no limit 1 ;
       
          ELSE
          SELECT ifnull(SUM(if(type<>'OUTPUT' and unique_id=id_no,qty*uprice,0))/SUM(if(type='OUTPUT'  and adid=id_no,qty*weight,0)),0) INTO bname  FROM Packing_d where no=v_no  group by no limit 1;
       
          END IF;
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_average_forecast_cost`$$
CREATE FUNCTION `get_average_forecast_cost`(v_no VARCHAR(200),v_id  VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname  DOUBLE;
         
       SELECT ifnull(SUM(qty*uprice),0) INTO bname  FROM forecast_d where no=v_no and unique_id=v_id  group by no limit 1 ;
         
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_batch_exp`$$
CREATE FUNCTION `get_batch_exp`(v_code  VARCHAR(200),v_batchno  VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
          SELECT if(expirydate='2050-01-01','',expirydate) INTO bname  FROM stran where code=v_code and batchno=v_batchno and ts='+' limit 1;
          
         IF (bname =''  or bname  IS NULL) THEN SET bname='2050-01-01';
         END IF;
        RETURN ifnull(bname,'2050-01-01');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_binlocation`$$
CREATE FUNCTION `get_binlocation`(bcode VARCHAR(20) ) RETURNS varchar(100) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE vcode VARCHAR(200);

          SELECT blocation INTO vcode from si where code=bcode limit 1;

          RETURN vcode;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_branch`$$
CREATE FUNCTION `get_branch`(v_custref VARCHAR(200) ,v_code  VARCHAR(200) ) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
          SELECT descr INTO bname  FROM branch where custref=v_custref  and code=v_code limit 1;
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_branch_category`$$
CREATE FUNCTION `get_branch_category`(v_category VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname  VARCHAR(200);
          
          SELECT bcategory INTO bname from branches_d where branchcode=v_category;
               
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_budget`$$
CREATE FUNCTION `get_budget`(V_year VARCHAR(300),V_month VARCHAR(300),V_code VARCHAR(300),V_costcenter VARCHAR(300),V_branch VARCHAR(300)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;
           
         SELECT sum(amount/rate)  INTO s_qty FROM  jt where trantype='Budget' and  period=V_year and bmonth=V_month  and code=v_code  and costcenter like if(V_costcenter='ALL','%%',V_costcenter) and profitc like if(V_branch='ALL','%%',V_branch);
     

        IF (s_qty IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_budget_todate`$$
CREATE FUNCTION `get_budget_todate`(V_year VARCHAR(300),V_month VARCHAR(300),V_code VARCHAR(300),V_costcenter VARCHAR(300),V_branch  VARCHAR(300)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

 
         SELECT sum(amount/rate)  INTO s_qty FROM  jt where trantype='Budget' and  period=V_year and bmonth<=V_month  and code=v_code   and costcenter like if(V_costcenter='ALL','%%',V_costcenter) and profitc like if(V_branch='ALL','%%',V_branch)  group by code;

        IF (s_qty IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_category`$$
CREATE FUNCTION `get_category`(v_code VARCHAR(200),v_type  VARCHAR(200) ) RETURNS varchar(80) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(80);
          IF  v_type='stocks' THEN
          SELECT categ INTO bname  FROM si where code=v_code group by code limit 1;
          ELSE
          SELECT category INTO bname  FROM accounts where code=v_code group by code limit 1;
          END IF;
     
        RETURN ifnull(bname,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_cheque`$$
CREATE FUNCTION `get_cheque`(v_account VARCHAR(200),v_chequeno VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname   VARCHAR(200);
          
          SELECT ifnull(remarks,'NOT SET') INTO bname  FROM journal_transactions where code=v_account and cheque_no=v_chequeno and transign='-' limit 1;
     
        RETURN ifnull(bname,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_costcenter_category`$$
CREATE FUNCTION `get_costcenter_category`(v_category VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname  VARCHAR(200);
          
          SELECT category INTO bname from costcenter where code=v_category;
               
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_cost_recipe`$$
CREATE FUNCTION `get_cost_recipe`(v_code VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
         
           SELECT cost  INTO bname  from (
           SELECT a.code,a.descr,sum(b.cost) as cost from si a,assembly_d b where recipe<>'' and a.recipe=b.no group by code,b.no
           union  SELECT a.code,a.descr,sum(a.cost) as cost from si a where recipe=''  group by code ) as  a where code=v_code;
     
        RETURN ifnull(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_CSN`$$
CREATE FUNCTION `get_CSN`(v_aircraft VARCHAR(200)) RETURNS int(11)
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
       DECLARE b_name DOUBLE;
       DECLARE D_DATE date;       
       DECLARE AIRCRAFT_CSN DOUBLE;
          
          select ddate INTO D_DATE from aircraft where ainfo=v_aircraft;

          select ifnull(totalflightcycles,0) INTO AIRCRAFT_CSN from aircraft where ainfo=v_aircraft;

          select ifnull(SUM(totalcycle),0) INTO bname from flight_log_post where posted=1 and ldate>=D_DATE and  flightreg=v_aircraft;
          
          SET b_name=bname+AIRCRAFT_CSN;
         
     
        RETURN IFNULL(b_name,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_CSN_PERIOD`$$
CREATE FUNCTION `get_CSN_PERIOD`(v_aircraft VARCHAR(200),v_period VARCHAR(200)) RETURNS int(11)
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
          
          select SUM(totalairtime) INTO bname from flight_log_post where orderno<>'' and ldate between   date_add(date(now()), interval -v_period  day) and date(now()) and flightreg=v_aircraft;
     
        RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_currency_factor`$$
CREATE FUNCTION `get_currency_factor`(V_currency VARCHAR(200) ,V_period VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          SELECT IFNULL(amount,1) INTO s_qty FROM exchangerates WHERE code=V_currency AND period=V_period LIMIT 1;

          IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=1;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_customer_branch`$$
CREATE FUNCTION `get_customer_branch`(v_code VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_cogs VARCHAR(200);

       SELECT ifnull(profitc,'') INTO s_cogs from invoices where clientcode =v_code LIMIT 1 ;

          if (s_cogs='' or isnull(s_cogs)) then
          SELECT ifnull(profitc,'') INTO s_cogs from orders where clientcode =v_code LIMIT 1;
          END IF;

          if (s_cogs='' or isnull(s_cogs)) then
          SELECT ifnull(profitc,'') INTO s_cogs from ar_prepayment where ccode =v_code LIMIT 1;
          END IF;
          RETURN s_cogs;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_customer_order_details`$$
CREATE FUNCTION `get_customer_order_details`(v_orderno VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_details VARCHAR(200);

          SELECT  DATE_FORMAT(duedate,'%d/%m/%Y') INTO s_details from orders where invno=v_orderno LIMIT 1 ;

         RETURN IFNULL(s_details,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_cu_invoice_no`$$
CREATE FUNCTION `get_cu_invoice_no`(v_code VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_cuno VARCHAR(500);

          SELECT  esd_cu_invoice_number INTO s_cuno from esd_invoices_log where invoice_number=v_code and signed=1 LIMIT 1 ;

          RETURN ifnull(s_cuno,"");
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_dosage_name`$$
CREATE FUNCTION `get_dosage_name`(bcode VARCHAR(100) ) RETURNS varchar(100) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE vcode VARCHAR(100);

          SELECT dosage INTO vcode from si where code=bcode limit 1;

          RETURN vcode;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_flightlog`$$
CREATE FUNCTION `get_flightlog`(V_year VARCHAR(200),V_month VARCHAR(200),V_costcenter VARCHAR(200),v_noncommerical varchar(5)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_costcenter='ALL' THEN 
           
         SELECT sum(flt_time)  INTO s_qty FROM  flightmanifest a, flightmanifest_d b where a.orderno=b.orderno and posted=1 and month(tdate)=V_month and year(tdate)=V_year and ccommercial=v_noncommerical ;

        END IF;

        IF V_costcenter<>'ALL' THEN 
           
         SELECT sum(flt_time)  INTO s_qty FROM  flightmanifest a, flightmanifest_d b where a.orderno=b.orderno and posted=1 and month(tdate)=V_month and year(tdate)=V_year and flightreg=V_costcenter and ccommercial=v_noncommerical group by flightreg;

        END IF;



        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_flightlog_todate`$$
CREATE FUNCTION `get_flightlog_todate`(V_year VARCHAR(200),V_month VARCHAR(200),V_costcenter VARCHAR(200),v_noncommerical varchar(5)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_costcenter='ALL' THEN 
           
         SELECT sum(flt_time)  INTO s_qty FROM  flightmanifest a, flightmanifest_d b where a.orderno=b.orderno and posted=1 and month(tdate)<=V_month and year(tdate)=V_year and ccommercial=v_noncommerical ;

        END IF;

        IF V_costcenter<>'ALL' THEN 
           
         SELECT sum(flt_time)  INTO s_qty FROM  flightmanifest a, flightmanifest_d b where a.orderno=b.orderno and posted=1 and month(tdate)<=V_month and year(tdate)=V_year and flightreg=V_costcenter and ccommercial=v_noncommerical group by flightreg;

        END IF;


        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_fuel`$$
CREATE FUNCTION `get_fuel`(v_journeylog VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
          
          select SUM(qty) INTO bname  from (select qty  from vinvoices a,vinvoices_details b where a.invno=b.invno and fuel=1 and a.posted<>0 and journeylog=v_journeylog union all  select qty from issue a,issue_d b where a.`no`=b.no and fuel=1 and a.posted<>0 and journeylog=v_journeylog ) as a ;
     
        RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_generic_name`$$
CREATE FUNCTION `get_generic_name`(bcode VARCHAR(100) ) RETURNS varchar(100) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE vcode VARCHAR(100);

          SELECT concat(genericname,' ', formulation) INTO vcode from si where code=bcode limit 1;

          RETURN vcode;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_hrs_budget`$$
CREATE FUNCTION `get_hrs_budget`(V_year VARCHAR(200),V_month VARCHAR(200),V_code VARCHAR(200),V_costcenter VARCHAR(200),V_type VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

        IF V_costcenter='ALL' THEN 

          IF V_type='FUEL' THEN
            SELECT sum(fuel)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth=V_month group by costcenter;
           END IF;
            IF V_type<>'FUEL' THEN 
            SELECT sum(amount) INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth=V_month and code=v_code group by code;
          
          END IF;      
         
        END IF;

        IF V_costcenter<>'ALL' THEN 

           IF V_type='FUEL' THEN
            SELECT sum(fuel)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth=V_month  and costcenter=V_costcenter group by costcenter;
           END IF;
           IF V_type<>'FUEL' THEN 
            SELECT sum(amount)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth=V_month  and code=v_code and costcenter=V_costcenter limit 1;
          
          END IF;   
         
        END IF;


        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_hrs_budget_todate`$$
CREATE FUNCTION `get_hrs_budget_todate`(V_year VARCHAR(200),V_month VARCHAR(200),V_code VARCHAR(200),V_costcenter VARCHAR(200),V_type VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

       IF V_costcenter='ALL' THEN 

          IF V_type='FUEL' THEN
            SELECT sum(fuel)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth<=V_month group by costcenter;
          END IF;

           IF V_type<>'FUEL' THEN 
            SELECT sum(amount)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth<=V_month and code=v_code group by code;
          
          END IF;      
         
        END IF;

        IF V_costcenter<>'ALL' THEN 

           IF V_type='FUEL' THEN 
             SELECT sum(fuel)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth<=V_month  and costcenter=V_costcenter group by costcenter;
           END IF;
           IF V_type<>'FUEL' THEN 
            SELECT sum(amount)  INTO s_qty FROM  jt_fuel where trantype='Budget' and  period=V_year and bmonth<=V_month  and code=v_code and costcenter=V_costcenter limit 1;
          
          END IF;   
         
        END IF;


        IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;
        END IF;
        RETURN s_qty;
  END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_hscode`$$
CREATE FUNCTION `get_hscode`(v_code VARCHAR(200),v_type  VARCHAR(200) ) RETURNS varchar(80) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(80);
          IF  v_type='stocks' THEN
          SELECT hscode INTO bname  FROM si where code=v_code group by code limit 1;
          ELSE
          SELECT hscode INTO bname  FROM accounts where code=v_code group by code limit 1;
          END IF;
     
        RETURN ifnull(bname,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_if_vehicle`$$
CREATE FUNCTION `get_if_vehicle`(v_vehicle VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
          select vid INTO bname from Vehicles where vid=v_vehicle;
     
        RETURN IFNULL(bname,'000000');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_kms`$$
CREATE FUNCTION `get_kms`(v_vehicle VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
       DECLARE b_name DOUBLE;
       DECLARE D_DATE date;
       DECLARE vehicle_km DOUBLE;      
          
          select pmileageasat INTO D_DATE from vehicles where vid=v_vehicle;

          select ifnull(pmileage,0) INTO vehicle_km from vehicles where vid=v_vehicle;         

          select ifnull(SUM(totalkms),0) INTO bname from journeylog where posted=1 and journeydate>=D_DATE and  vehicle=v_vehicle;
          
          SET b_name=bname+vehicle_km;
         
     
        RETURN IFNULL(b_name,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_KMS_PERIOD`$$
CREATE FUNCTION `get_KMS_PERIOD`(v_aircraft VARCHAR(200),v_period VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
          
          select SUM(totalkms) INTO bname from journeylog where journeyid<>'' and journeydate between   date_add(date(now()), interval -v_period  day) and date(now()) and vehicle=v_aircraft;
     
        RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_loading_d`$$
CREATE FUNCTION `get_loading_d`(v_vid VARCHAR(200),v_cargo VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
          select description INTO bname from vehicles_load where vid=v_vid and  cargo=v_cargo;
     
        RETURN IFNULL(bname,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_loading_off`$$
CREATE FUNCTION `get_loading_off`(v_journeyid VARCHAR(200),v_type VARCHAR(200)) RETURNS decimal(10,0)
    DETERMINISTIC
BEGIN
       
       DECLARE D_QTY DOUBLE;       
       
           IF v_type='LOADING' THEN
          
            SELECT sum(if(offqty>50,offqty/1000,offqty)) INTO D_QTY from journeylog_d WHERE CSALE=1 and  journeyid=v_journeyid GROUP BY journeyid;
                  
           END IF;

           IF v_type='OFFLOADING' THEN
          
            SELECT sum(if(offqty>50,offqty/1000,offqty)) INTO D_QTY from journeylog_d WHERE CSALE=2 and  journeyid=v_journeyid  GROUP BY journeyid;
                  
           END IF;

         RETURN IFNULL(D_QTY,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_maincateg`$$
CREATE FUNCTION `get_maincateg`(v_categ VARCHAR(20) ) RETURNS varchar(100) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
        SELECT main_categ INTO bname  FROM sc where  code=v_categ;
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_measurements_pu`$$
CREATE FUNCTION `get_measurements_pu`(v_code CHAR(200),v_pu CHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_qty VARCHAR(200);

          SELECT  concat('L',length, 'W',width,'H',height) INTO s_qty from puweight where code =v_code and punit =v_pu LIMIT 1;

          IF (s_qty  IS NULL) THEN SET s_qty='';

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_netweight_pu`$$
CREATE FUNCTION `get_netweight_pu`(v_code CHAR(200),v_pu CHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          SELECT  netweight INTO s_qty from puweight where code =v_code and punit =v_pu LIMIT 1;

          IF (s_qty  IS NULL) THEN SET s_qty=0;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_notes`$$
CREATE FUNCTION `get_notes`(v_code VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_notes VARCHAR(200);

          SELECT  notes INTO s_notes from si where code =v_code LIMIT 1 ;

         RETURN s_notes;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_own`$$
CREATE FUNCTION `get_own`(
	`v_vehicle` VARCHAR(200)
) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       
       DECLARE D_own  VARCHAR(200);       
       
          
          select account_category INTO D_own from vehicles where vid=v_vehicle;
                  
     
        RETURN D_own;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_payref`$$
CREATE FUNCTION `get_payref`(v_code  VARCHAR(200) ) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE ppayref VARCHAR(200);
          
         select group_concat(concat(payname,':',payref)) INTO ppayref from pos_payment_details where receiptno=v_code and payref<>'' group by v_code;
 
     
        RETURN ppayref;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_payroll_hrs`$$
CREATE FUNCTION `get_payroll_hrs`(v_staffno VARCHAR(200)) RETURNS decimal(12,2)
    DETERMINISTIC
BEGIN
       DECLARE bname decimal(12,2);
          select ifnull(sum(hrs),0) INTO bname from payroll_hr where staffcode=v_staffno group by staffcode ;     
           
		RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_price`$$
CREATE FUNCTION `get_price`(v_journeylog VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
          
          select SUM(amount) INTO bname  from (select b.amount as amount  from vinvoices a,vinvoices_details b where a.invno=b.invno and fuel=1 and a.posted<>0 and journeylog=v_journeylog union all  select total as amount from issue a,issue_d b where a.`no`=b.no and fuel=1 and a.posted<>0 and journeylog=v_journeylog ) as a ;
     
        RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_price_forecourt`$$
CREATE FUNCTION `get_price_forecourt`(v_product VARCHAR(200),v_has_price VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
       DECLARE b_name DOUBLE;
	   DECLARE b_names DOUBLE;
	   
       
		IF (v_has_price<>'NONE' AND v_has_price<>'') THEN
		SELECT uprice INTO b_names FROM pricelist_d where no=v_has_price and code=v_product limit 1;
                   
		ELSE
		 SELECT price INTO b_names FROM si where code=v_product limit 1;
       
		END IF;
		RETURN IFNULL(b_names,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_pump_item`$$
CREATE FUNCTION `get_pump_item`(v_tank VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_qty VARCHAR(200);

          SELECT  itemcode INTO s_qty from sl where code =v_tank LIMIT 1 ;

         RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_Pump_Out`$$
CREATE FUNCTION `get_Pump_Out`(v_shift VARCHAR(200),v_pump VARCHAR(200)) RETURNS decimal(20,4)
    DETERMINISTIC
BEGIN
       DECLARE s_qty VARCHAR(200);

           SELECT  sum(qty) INTO s_qty from transfer a, transfer_d b  where a.no=b.no and pout=1 and posted=1 and shiftno=v_shift and pump=v_pump  LIMIT 1 ;


         RETURN IFNULL(s_qty,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_qtyr`$$
CREATE FUNCTION `get_qtyr`(v_orderno VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_qno VARCHAR(200);

          SELECT  qtyr INTO s_qno from si where code=v_orderno LIMIT 1 ;

         RETURN IFNULL(s_qno ,1);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_Recipe_item_count`$$
CREATE FUNCTION `get_Recipe_item_count`(v_code VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_notes VARCHAR(200);

          SELECT  count(*) as total INTO s_notes from assembly_d where no =v_code LIMIT 1 ;

         RETURN s_notes;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_recipe_no`$$
CREATE FUNCTION `get_recipe_no`(v_orderno VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_rno VARCHAR(200);

          SELECT  recipe INTO s_rno from si where code=v_orderno LIMIT 1 ;

         RETURN IFNULL(s_rno ,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_recipe_no_packinglist`$$
CREATE FUNCTION `get_recipe_no_packinglist`(v_orderno VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_rno VARCHAR(200);

          SELECT  if(chaspackinglist=1,recipe,'') INTO s_rno from si where code=v_orderno LIMIT 1 ;

         RETURN IFNULL(s_rno ,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_smallest_qty`$$
CREATE FUNCTION `get_smallest_qty`(qty DOUBLE,v_pu CHAR(20)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          SELECT IFNULL(factor,1) INTO s_qty FROM pu WHERE code=v_pu LIMIT 1;

          IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=1;

          END IF;

        RETURN s_qty*qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_stock_qty`$$
CREATE FUNCTION `get_stock_qty`(v_code CHAR(200),v_loc CHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          
          select ifnull(sum(if(ts='+',tqty,tqty*-1))/get_smallest_qty(1,if(sunit is null or sunit='',sunit,sunit)),0)  INTO s_qty from stran a,si b where a.code=b.code and a.code=v_code and a.loc=v_loc  group by a.code,a.loc;

          IF (s_qty  IS NULL) THEN SET s_qty=0;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_stock_quantity`$$
CREATE FUNCTION `get_stock_quantity`(v_code CHAR(200),v_loc CHAR(200)) RETURNS double
BEGIN
       DECLARE s_qty DOUBLE;

          
          select ifnull(sum(if(ts='+',tqty,tqty*-1)),0)  INTO s_qty from stran a,si b where a.code=b.code and a.code=v_code and a.loc=v_loc  group by a.code,a.loc;

          IF (s_qty  IS NULL) THEN SET s_qty=0;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_subcategory`$$
CREATE FUNCTION `get_subcategory`(v_code VARCHAR(200),v_type  VARCHAR(200) ) RETURNS varchar(80) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(80);
          IF  v_type='stocks' THEN
          SELECT SUBCATEG INTO bname  FROM si where code=v_code group by code limit 1;
          ELSE
          SELECT category INTO bname  FROM accounts where code=v_code group by code limit 1;
          END IF;
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_supplier`$$
CREATE FUNCTION `get_supplier`(v_code  VARCHAR(200) ) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE bname VARCHAR(200);
          
          SELECT manu INTO bname  FROM si where code=v_code;
     
        RETURN bname;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_tel`$$
CREATE FUNCTION `get_tel`(v_code VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_tel VARCHAR(200);

          SELECT  tel2 INTO s_tel from clients where code =v_code LIMIT 1 ;

         RETURN s_tel;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_tsN`$$
CREATE FUNCTION `get_tsN`(v_aircraft VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
       DECLARE b_name DOUBLE;
       DECLARE D_DATE date;
       DECLARE AIRCRAFT_TSN DOUBLE;      
          
          select ddate INTO D_DATE from aircraft where ainfo=v_aircraft;

          select ifnull(totalflighthours,0) INTO AIRCRAFT_TSN from aircraft where ainfo=v_aircraft;         

          select ifnull(SUM(totalairtime),0) INTO bname from flight_log_post where posted=1 and ldate>=D_DATE and  flightreg=v_aircraft;
          
          SET b_name=bname+AIRCRAFT_TSN;
         
     
        RETURN IFNULL(b_name,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_TSN_PERIOD`$$
CREATE FUNCTION `get_TSN_PERIOD`(v_aircraft VARCHAR(200),v_period VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
          
          select SUM(totalairtime) INTO bname from flight_log_post where orderno<>'' and ldate between   date_add(date(now()), interval -v_period  day) and date(now()) and flightreg=v_aircraft;
     
        RETURN IFNULL(bname,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_unit_p`$$
CREATE FUNCTION `get_unit_p`(v_code VARCHAR(200),v_pu VARCHAR(200),v_rate double,v_wich_price VARCHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE bname DOUBLE;
       DECLARE b_name DOUBLE;
	   DECLARE b_names DOUBLE;
	   
       
		IF v_wich_price<>'BASICPRICE' THEN
		SELECT cost/get_smallest_qty(1,sunit)*get_smallest_qty(1,v_pu)*v_rate INTO b_names FROM si where code=v_code limit 1;
       
		ELSE
		SELECT basicprice/get_smallest_qty(1,sunit)*get_smallest_qty(1,v_pu)*v_rate INTO b_names FROM si where code=v_code limit 1;
       
		END IF;
		RETURN IFNULL(b_names,0);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_vat_status`$$
CREATE FUNCTION `get_vat_status`(v_code VARCHAR(200),v_status VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_qty VARCHAR(200);

          SELECT  if(taxable=0,'Exempt',if(taxable=1,'Taxable','Zero Rated')) INTO s_qty from si where code =v_code;

         RETURN ifnull(s_qty,v_status);
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_volume_pu`$$
CREATE FUNCTION `get_volume_pu`(v_code CHAR(200),v_pu CHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          SELECT  length*width*height INTO s_qty from puweight where code =v_code and punit =v_pu LIMIT 1;

          IF (s_qty  IS NULL) THEN SET s_qty=0;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `get_weight_pu`$$
CREATE FUNCTION `get_weight_pu`(v_code CHAR(200),v_pu CHAR(200)) RETURNS double
    DETERMINISTIC
BEGIN
       DECLARE s_qty DOUBLE;

          SELECT  puweight INTO s_qty from puweight where code =v_code and punit =v_pu LIMIT 1;

          IF (s_qty < 0 or s_qty  IS NULL) THEN SET s_qty=0;

          END IF;

        RETURN s_qty;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `has_pricelist`$$
CREATE FUNCTION `has_pricelist`(v_branch VARCHAR(200),V_itemcode VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_branch varchar(200);

	SELECT if(pricelist='','NONE',pricelist) INTO s_branch FROM pricelist_d a,branches_d b where a.no=b.pricelist and branchcode=v_branch AND a.code=V_itemcode  limit 1;
                                     

         RETURN IFNULL(s_branch ,'NONE');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `last_log_date`$$
CREATE FUNCTION `last_log_date`(v_aircraft VARCHAR(200)) RETURNS date
    DETERMINISTIC
BEGIN
       
       DECLARE D_DATE date;       
       
          
          select max(ldate) INTO D_DATE from flight_log_post where posted=1 and  flightreg=v_aircraft;
                  
     
        RETURN D_DATE;
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `last_station`$$
CREATE FUNCTION `last_station`(v_vehicle VARCHAR(200)) RETURNS varchar(200) CHARSET latin1
    DETERMINISTIC
BEGIN
       
       DECLARE V_STATION VARCHAR(200);       
              
           SET V_STATION='';
      
           select IFNULL(if(a.endstation='',b.currentbase,a.endstation),'')  INTO V_STATION from  ( select ifnull(if(endstation='',CONCAT('TRANSIT FROM ',startstation),endstation),'') as endstation,vehicle from journeylog a where vehicle=v_vehicle order by journeydate desc limit 1  ) as a,vehicles b where b.vid=a.vehicle ;
                 
           if V_STATION=''  then
               SELECT currentbase  INTO V_STATION from vehicles where vid=v_vehicle limit 1;
           end if;
     
        RETURN IFNULL(V_STATION,'');
 END$$

-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS `mysq_replace_str`$$
CREATE FUNCTION `mysq_replace_str`(v_orderno VARCHAR(500)) RETURNS varchar(500) CHARSET latin1
    DETERMINISTIC
BEGIN
       DECLARE s_details VARCHAR(200);

          SELECT  replace(v_orderno,'"','') INTO s_details;

         RETURN IFNULL(s_details,'');
 END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `create_pu`$$
CREATE PROCEDURE `create_pu`(IN pcode VARCHAR(200),IN descr VARCHAR(100))
BEGIN
        
	INSERT INTO pu(code,descr,factor)
	VALUES (pcode,descr,1);
END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_production_forcast`$$
CREATE PROCEDURE `do_production_forcast`(IN v_code VARCHAR(200),IN v_descr VARCHAR(100),in v_stdate date,IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_glcode VARCHAR(300),IN v_trancode VARCHAR(200),IN v_trandesc VARCHAR(200),IN v_source VARCHAR(200),IN v_loc VARCHAR(200),IN v_ts VARCHAR(10),IN v_serialized int(1),IN v_serial VARCHAR(200),IN V_staff VARCHAR(40))
BEGIN
        
        DECLARE v_nb  VARCHAR(200);
        DECLARE tempqty DOUBLE; 
        DECLARE tmpqty DOUBLE;
        DECLARE iprice DOUBLE;
        DECLARE itc DOUBLE;
        DECLARE itc1 DOUBLE;
        DECLARE v_count INTEGER;
        DECLARE tqty DOUBLE;
        DECLARE uprice DOUBLE;
        SET v_count = 0;
        SET uprice = v_total/get_smallest_qty(v_qty,v_pu);

	SELECT count(1)
	INTO v_count
	FROM pu
	WHERE code = v_pu limit 1;

        	IF v_count < 1 THEN
		call create_pu(v_pu,v_pu);
	END IF;
 
        SET tqty = get_smallest_qty(v_qty,v_pu);
           
	

	IF v_qty <> 0 THEN
		INSERT INTO stran_forecast (code,descr,stdate,qty,pu,price,total,tqty,tt,staff,sdate,glcode,trancode,trandesc,source,sourced,loc,ts,uprice,serial,batchno)
		VALUES (v_code,v_descr,v_stdate,v_qty,v_pu,v_price,v_total,tqty,v_tt,v_staff,v_stdate,v_glcode,v_trancode,v_trandesc,v_source,v_source,v_loc,v_ts,uprice,v_serial,v_glcode);              
               	                  
	END IF;
                  
	
END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_production_forcast_new`$$
CREATE PROCEDURE `do_production_forcast_new`(IN v_code VARCHAR(200),IN v_descr VARCHAR(100),in v_stdate date,IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_glcode VARCHAR(300),IN v_trancode VARCHAR(200),IN v_trandesc VARCHAR(200),IN v_source VARCHAR(200),IN v_loc VARCHAR(200),IN v_ts VARCHAR(10),IN v_serialized int(1),IN v_serial VARCHAR(200),IN V_staff VARCHAR(40),IN V_ubfeet  VARCHAR(40),IN v_bfeetqty1 VARCHAR(40),IN v_bfeetqty2 VARCHAR(40),IN v_bfeetqty_add1 VARCHAR(40),IN v_bfeetqty_add2 VARCHAR(40),IN v_cwna VARCHAR(40),IN v_clna VARCHAR(40))
BEGIN
        
        DECLARE v_nb  VARCHAR(200);
        DECLARE tempqty DOUBLE; 
        DECLARE tmpqty DOUBLE;
        DECLARE iprice DOUBLE;
        DECLARE itc DOUBLE;
        DECLARE itc1 DOUBLE;
        DECLARE v_count INTEGER;
        DECLARE tqty DOUBLE;
        DECLARE uprice DOUBLE;
        SET v_count = 0;
        SET uprice = v_total/get_smallest_qty(v_qty,v_pu);

	SELECT count(1)
	INTO v_count
	FROM pu
	WHERE code = v_pu limit 1;

        	IF v_count < 1 THEN
		call create_pu(v_pu,v_pu);
	END IF;
 
        SET tqty = get_smallest_qty(v_qty,v_pu);
           
	

	IF v_qty <> 0 THEN
		INSERT INTO stran_forecast (code,descr,stdate,qty,pu,price,total,tqty,tt,staff,sdate,glcode,trancode,trandesc,source,sourced,loc,ts,uprice,serial,batchno,ubfeet,bfeetqty1,bfeetqty2,bfeetqty_add1,bfeetqty_add2,cwna,clna)
		VALUES (v_code,v_descr,v_stdate,v_qty,v_pu,v_price,v_total,tqty,v_tt,v_staff,v_stdate,v_glcode,v_trancode,v_trandesc,v_source,v_source,v_loc,v_ts,uprice,v_serial,v_glcode,v_ubfeet,v_bfeetqty1,v_bfeetqty2,v_bfeetqty_add1,v_bfeetqty_add2,v_cwna,v_clna);              
               	                  
	END IF;
                  
	
END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_production_forcast_new_count`$$
CREATE PROCEDURE `do_production_forcast_new_count`(IN v_code VARCHAR(200),IN v_descr VARCHAR(100),in v_stdate date,IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_glcode VARCHAR(300),IN v_trancode VARCHAR(200),IN v_trandesc VARCHAR(200),IN v_source VARCHAR(200),IN v_loc VARCHAR(200),IN v_ts VARCHAR(10),IN v_serialized int(1),IN v_serial VARCHAR(200),IN V_staff VARCHAR(40),IN V_ubfeet  VARCHAR(40),IN v_bfeetqty1 VARCHAR(40),IN v_bfeetqty2 VARCHAR(40),IN v_bfeetqty_add1 VARCHAR(40),IN v_bfeetqty_add2 VARCHAR(40),IN v_cwna VARCHAR(40),IN v_clna VARCHAR(40),IN v_itemcount VARCHAR(40),IN v_main_item  VARCHAR(200))
BEGIN
        
        DECLARE v_nb  VARCHAR(200);
        DECLARE tempqty DOUBLE; 
        DECLARE tmpqty DOUBLE;
        DECLARE iprice DOUBLE;
        DECLARE itc DOUBLE;
        DECLARE itc1 DOUBLE;
        DECLARE v_count INTEGER;
        DECLARE tqty DOUBLE;
        DECLARE uprice DOUBLE;
        SET v_count = 0;
        SET uprice = v_total/get_smallest_qty(v_qty,v_pu);

	SELECT count(1)
	INTO v_count
	FROM pu
	WHERE code = v_pu limit 1;

        	IF v_count < 1 THEN
		call create_pu(v_pu,v_pu);
	END IF;
 
        SET tqty = get_smallest_qty(v_qty,v_pu);
           
	

	IF v_qty <> 0 THEN
		INSERT INTO stran_forecast (code,descr,stdate,qty,pu,price,total,tqty,tt,staff,sdate,glcode,trancode,trandesc,source,sourced,loc,ts,uprice,serial,batchno,ubfeet,bfeetqty1,bfeetqty2,bfeetqty_add1,bfeetqty_add2,cwna,clna,itemcount,main_code)
		VALUES (v_code,v_descr,v_stdate,v_qty,v_pu,v_price,v_total,tqty,v_tt,v_staff,v_stdate,v_glcode,v_trancode,v_trandesc,v_source,v_source,v_loc,v_ts,uprice,v_serial,v_glcode,v_ubfeet,v_bfeetqty1,v_bfeetqty2,v_bfeetqty_add1,v_bfeetqty_add2,v_cwna,v_clna,v_itemcount,v_main_item);              
               	                  
	END IF;
                  
	
END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_siserial_sq`$$
CREATE PROCEDURE `do_siserial_sq`(IN v_code VARCHAR(200),IN v_serial VARCHAR(200),IN v_transign VARCHAR(10),IN v_tsn DOUBLE,IN v_csn DOUBLE,IN v_tso DOUBLE,IN v_cso DOUBLE,IN v_stdate DATE,IN v_loc VARCHAR(200),IN v_subloc VARCHAR(200))
BEGIN
	
        DECLARE v_count DOUBLE;

	SELECT count(1)
	INTO v_count
	FROM siserial
	WHERE code = v_code and serialno = v_serial 
	LIMIT 1;
	
        
	
		

	IF  v_transign='+' THEN
		IF v_count > 0 THEN
			
				UPDATE siserial SET tsn=tsn+v_tsn,csn=csn+V_csn,tso=tso+V_tso,cso=cso+V_cso
				WHERE code = v_code AND serialno = v_serial;
			

		ELSE

			INSERT into siserial (code,serialno,pstatus,screate,dcreate,dmodify,smodify,tsn,csn,mdate,tso,cso,location,sublocation,active)
			VALUES(v_code,v_serial,'New',username,now(),username,now(), v_tsn,v_csn,v_stdate,v_tso,v_cso,v_loc,v_subloc,1);
		END IF;   
	ELSE
		IF v_count> 0 THEN
		         

 			UPDATE siserial SET tsn=tsn-v_tsn,csn=csn-V_csn,tso=tso-V_tso,cso=cso-V_cso
				WHERE code = v_code AND serialno = v_serial;
		ELSE
			INSERT into siserial (code,serialno,pstatus,screate,dcreate,dmodify,smodify,tsn,csn,mdate,tso,cso,location,sublocation,active)
			VALUES(v_code,v_serial,'New',username,now(),username,now(), v_tsn,v_csn,v_stdate,v_tso,v_cso,v_loc,v_subloc,1);	
	
		END IF;
	END IF;

				


END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_siserial_transactions`$$
CREATE PROCEDURE `do_siserial_transactions`(IN v_code VARCHAR(200),IN v_serial VARCHAR(100),IN v_stdate date,IN v_staff VARCHAR(200),IN v_trancode VARCHAR(200),IN v_trantype VARCHAR(200),IN v_loc VARCHAR(200),IN v_subloc VARCHAR(200),IN v_transign  varchar(10),IN v_tsn DOUBLE,IN v_csn DOUBLE,IN v_tso DOUBLE,IN v_cso DOUBLE)
BEGIN
        
        
        DECLARE v_qty DOUBLE;
       
        SET v_qty = v_tsn + v_csn + v_tso + v_cso;
           
	

	IF v_qty <> 0 THEN
		INSERT INTO siserialtran(code,serialno,mtdate,staff,staffdate,trandcode,trantype,location,sublocation,transign,tsn,csn,tso,cso)
		VALUES (v_code,v_serial,v_stdate,v_staff,now(),v_trancode,v_trantype,v_loc,v_subloc,v_transign,v_tsn,v_csn,v_tso,v_cso);              
               	                  
	END IF;
                  
	
	IF v_qty <> 0 then
               CALL do_siserial_sq(v_code,v_serial,v_transign,v_tsn,v_csn,v_tso,v_cso,v_stdate,v_loc,v_subloc) ; 	
	END IF;

	

END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_stock_sq`$$
CREATE PROCEDURE `do_stock_sq`(IN v_code VARCHAR(200),IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_ts VARCHAR(10),IN v_loc VARCHAR(200),IN v_tqty DOUBLE)
BEGIN
	DECLARE v_quantity DOUBLE;
	DECLARE v_totalcost DOUBLE;
	DECLARE v_tq DOUBLE;
        DECLARE v_tqc DOUBLE;
	DECLARE v_w DOUBLE;
	DECLARE v_count	INTEGER;
	DECLARE username VARCHAR(200);
	DECLARE v_wavgc DOUBLE;

	SELECT count(1)
	INTO v_count
	FROM sq
	WHERE code = v_code and loc=v_loc LIMIT 1;
	
        set v_tqc = get_smallest_qty(v_qty,v_pu);
set v_wavgc=v_total/v_tqc;
	
		SELECT 
		quantity,
		totalcost,
                                   IFNULL(totalcost/quantity,wavgc) as tq,
		wavgc as w
		INTO
		v_quantity,
 		v_totalcost,
		v_tq,
		v_w
                                   FROM sq WHERE code = v_code AND loc = v_loc limit 1;

	IF  v_ts='+' THEN
		IF v_count > 0 THEN
			IF V_wavgc <> 0 THEN
				UPDATE  sq SET quantity=quantity+v_tqc,wavgc=v_wavgc
				WHERE code = v_code  AND loc = v_loc;
			ELSE
				UPDATE sq SET quantity=quantity+v_tqc,wavgc=v_wavgc
				WHERE code = v_code AND loc = v_loc;
			END IF;

		ELSE

			INSERT INTO sq (code,loc,totalcost,quantity,qty,lastupdated,updatedby,datecreated,createdby,wavgc)
			VALUES(v_code,v_loc,v_total,v_tqc,v_qty,current_date(),username,current_date(),username ,v_wavgc);
		END IF;   
	ELSE
		IF v_count> 0 THEN
		         

 			UPDATE sq SET totalcost=totalcost-v_total,
			quantity=quantity-v_tqc 
			WHERE code = v_code and loc = v_loc;
		ELSE
			INSERT INTO sq (code,loc,totalcost,quantity,qty,lastupdated,updatedby,datecreated,createdby,wavgc)
			VALUES(v_code,v_loc,v_total,v_tqc*-1,v_tqc*-1,current_date(),username,current_date(),username ,v_wavgc);	
	
		END IF;
	END IF;

				


END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_stock_sq_new`$$
CREATE PROCEDURE `do_stock_sq_new`(IN v_code VARCHAR(200),IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_ts VARCHAR(10),IN v_loc VARCHAR(200),IN v_tqty DOUBLE)
BEGIN
	DECLARE v_quantity DOUBLE;
	DECLARE v_totalcost DOUBLE;
	DECLARE v_tq DOUBLE;
        DECLARE v_tqc DOUBLE;
	DECLARE v_w DOUBLE;
	DECLARE v_count	INTEGER;
	DECLARE username VARCHAR(200);
	DECLARE v_wavgc DOUBLE;

	SELECT count(1)
	INTO v_count
	FROM sq
	WHERE code = v_code and loc=v_loc LIMIT 1;
	
        set v_tqc = get_smallest_qty(v_qty,v_pu);
set v_wavgc=v_total/v_tqc;
	
		SELECT 
		quantity,
		totalcost,
                                   IFNULL(totalcost/quantity,wavgc) as tq,
		wavgc as w
		INTO
		v_quantity,
 		v_totalcost,
		v_tq,
		v_w
                                   FROM sq WHERE code = v_code AND loc = v_loc limit 1;

	IF  v_ts='+' THEN
		IF v_count > 0 THEN
			IF V_wavgc <> 0 THEN
				UPDATE  sq SET quantity=quantity+v_tqc,wavgc=((wavgc*quantity)+(v_wavgc*v_tqc))/(quantity+v_tqc)
				WHERE code = v_code  AND loc = v_loc;
			ELSE
				UPDATE sq SET quantity=quantity+v_tqc,wavgc=((wavgc*quantity)+(v_wavgc*v_tqc))/(quantity+v_tqc)
				WHERE code = v_code AND loc = v_loc;
			END IF;

		ELSE

			INSERT INTO sq (code,loc,totalcost,quantity,qty,lastupdated,updatedby,datecreated,createdby,wavgc)
			VALUES(v_code,v_loc,v_total,v_tqc,v_qty,current_date(),username,current_date(),username ,v_wavgc);
		END IF;   
	ELSE
		IF v_count> 0 THEN
		         

 			UPDATE sq SET totalcost=totalcost-v_total,
			quantity=quantity-v_tqc 
			WHERE code = v_code and loc = v_loc;
		ELSE
			INSERT INTO sq (code,loc,totalcost,quantity,qty,lastupdated,updatedby,datecreated,createdby,wavgc)
			VALUES(v_code,v_loc,v_total,v_tqc*-1,v_tqc*-1,current_date(),username,current_date(),username ,v_wavgc);	
	
		END IF;
	END IF;

				


END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_stock_transactions`$$
CREATE PROCEDURE `do_stock_transactions`(IN v_code VARCHAR(200),IN v_descr VARCHAR(100),in v_stdate date,IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_glcode VARCHAR(200),IN v_trancode VARCHAR(200),IN v_trandesc VARCHAR(200),IN v_source VARCHAR(200),IN v_loc VARCHAR(200),IN v_ts VARCHAR(10),IN v_serialized int(1),IN v_serial VARCHAR(200),IN V_staff VARCHAR(40))
BEGIN
        
        DECLARE v_nb  VARCHAR(200);
        DECLARE tempqty DOUBLE; 
        DECLARE tmpqty DOUBLE;
        DECLARE iprice DOUBLE;
        DECLARE itc DOUBLE;
        DECLARE itc1 DOUBLE;
        DECLARE v_count INTEGER;
        DECLARE tqty DOUBLE;
        DECLARE uprice DOUBLE;
        SET v_count = 0;
        SET uprice = v_total/get_smallest_qty(v_qty,v_pu);

	SELECT count(1)
	INTO v_count
	FROM pu
	WHERE code = v_pu limit 1;

        	IF v_count < 1 THEN
		call create_pu(v_pu,v_pu);
	END IF;
 
        SET tqty = get_smallest_qty(v_qty,v_pu);
           
	

	IF v_qty <> 0 THEN
		INSERT INTO stran (code,descr,stdate,qty,pu,price,total,tqty,tt,staff,sdate,glcode,trancode,trandesc,source,sourced,loc,ts,uprice,serial,batchno)
		VALUES (v_code,v_descr,v_stdate,v_qty,v_pu,v_price,v_total,tqty,v_tt,v_staff,now(),v_glcode,v_trancode,v_trandesc,v_source,v_source,v_loc,v_ts,uprice,v_serial,v_glcode);              
               	                  
	END IF;
                  
	
	IF v_qty <> 0 then
                		CALL do_stock_sq(v_code,v_qty,v_price,v_total,v_pu,v_tt,v_ts,v_loc,v_qty) ; 	
	END IF;

	

END$$

-- ------------------------------------------------------------
DROP PROCEDURE IF EXISTS `do_stock_transactions_new`$$
CREATE PROCEDURE `do_stock_transactions_new`(IN v_code VARCHAR(200),IN v_descr VARCHAR(100),in v_stdate date,IN v_qty DOUBLE, IN v_price DOUBLE,IN v_total DOUBLE,IN v_pu VARCHAR(200),IN v_tt VARCHAR(10),IN v_glcode VARCHAR(200),IN v_trancode VARCHAR(200),IN v_trandesc VARCHAR(200),IN v_source VARCHAR(200),IN v_loc VARCHAR(200),IN v_ts VARCHAR(10),IN v_serialized int(1),IN v_serial VARCHAR(200),IN V_staff VARCHAR(40),IN v_unit DOUBLE,IN v_unittotal DOUBLE,IN v_prunits2 VARCHAR(40),IN v_unitstd DOUBLE)
BEGIN
        
        DECLARE v_nb  VARCHAR(200);
        DECLARE tempqty DOUBLE; 
        DECLARE tmpqty DOUBLE;
        DECLARE iprice DOUBLE;
        DECLARE itc DOUBLE;
        DECLARE itc1 DOUBLE;
        DECLARE v_count INTEGER;
        DECLARE tqty DOUBLE;
        DECLARE uprice DOUBLE;
        SET v_count = 0;
        SET uprice = v_total/get_smallest_qty(v_qty,v_pu);

	SELECT count(1)
	INTO v_count
	FROM pu
	WHERE code = v_pu limit 1;

        	IF v_count < 1 THEN
		call create_pu(v_pu,v_pu);
	END IF;
 
        SET tqty = get_smallest_qty(v_qty,v_pu);
           
	

	IF v_qty <> 0 THEN
		INSERT INTO stran (code,descr,stdate,qty,pu,price,total,tqty,tt,staff,sdate,glcode,trancode,trandesc,source,sourced,loc,ts,uprice,serial,batchno,unit,unittotal,prunits2,unitstd)
		VALUES (v_code,v_descr,v_stdate,v_qty,v_pu,v_price,v_total,tqty,v_tt,v_staff,now(),v_glcode,v_trancode,v_trandesc,v_source,v_source,v_loc,v_ts,uprice,v_serial,v_glcode,v_unit,v_unittotal,v_prunits2,v_unitstd);              
               	                  
	END IF;
                  
	
	IF v_qty <> 0 then
                		CALL do_stock_sq(v_code,v_qty,v_price,v_total,v_pu,v_tt,v_ts,v_loc,v_qty) ; 	
	END IF;

	

END$$

DELIMITER ;